### ISSUE TITLE
react-native-webview dev dependency olarak eklenmiş

### ISSUE THREAD

**Issue by alimertcakar** [Infoset/infoset-react-native#1]
normal dependency olmalı.
`yarn add react-native-webview`

**Comment by onurcskun** [comment]
@alimertcakar peerDependency olarak ekli zaten, dev olanini localde calisirken kullaniyoruz, normalde peer kullaniyor. normal dependency eklersek projede react-native-webview var ise cakisacaktir

**Comment by alimertcakar** [comment]
anladım teşekkürler, temiz projede denedim webview ekli olmadığından hata verdi. peer dependency olduğunu farketmemişim.

**Comment by onurcskun** [comment]
@alimertcakar su an xcode 12.5 surumuyle ilgili cozemedigim bir sorun var react-native in. Ona cozum bulmaya calisiyorum :)
